# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('pid', models.CharField(default='', max_length=40)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(default='', max_length=40)),
                ('title', models.CharField(default='', max_length=100)),
                ('artist', models.CharField(default='', max_length=100)),
                ('danceability', models.DecimalField(decimal_places=1, max_digits=4)),
                ('energy', models.DecimalField(decimal_places=1, max_digits=4)),
                ('key', models.DecimalField(decimal_places=0, max_digits=2)),
                ('loudness', models.DecimalField(decimal_places=3, max_digits=6)),
                ('mode', models.DecimalField(decimal_places=0, max_digits=1)),
                ('speechiness', models.DecimalField(decimal_places=3, max_digits=6)),
                ('acousticness', models.DecimalField(decimal_places=4, max_digits=7)),
                ('instrumentalness', models.DecimalField(decimal_places=4, max_digits=7)),
                ('valence', models.DecimalField(decimal_places=3, max_digits=6)),
                ('tempo', models.DecimalField(decimal_places=3, max_digits=6)),
                ('duration', models.DecimalField(decimal_places=0, max_digits=6)),
                ('popularity', models.DecimalField(decimal_places=0, max_digits=3)),
                ('preview_url', models.CharField(default='', max_length=120)),
                ('cover_url', models.CharField(default='', max_length=120)),
                ('release_date', models.DateField()),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='engine.Song'),
        ),
    ]
